version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hakam@2000
      POSTGRES_DB: mydb
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs:
    build: .
    container_name: nestjs-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: Hakam@2000
      DATABASE_NAME: mydb

volumes:
  postgres_data:
